### PR TITLE
Feature/nonogram game

### PR DESCRIPTION
**Pull request by evpinheiro**
- This  branch contains the statement of a new puzzle for the project, the crucipixel game. 
- I started working with a formulation but it was not commited in this pull request.

### CODE REVIEW

**Comment by astersantana** [comment]
Hey @evpinheiro!
Thank you very much for proposing the puzzle. It sounds really interesting. 
I've made some small changes to the wording to make the statement clearer.
Next, I will try to solve it using MIP to see how hard it is. If everything goes fine, we will post it soon!

**Comment by evpinheiro** [comment]
@astersantana I remove the dots I left in the image.

**Comment by evpinheiro** [comment]
Besides, I added the formulation and implementation I have done. It is not written using the pattern correctly, because I considered we will change the notation to make the formulation cleaner, as you have already done.

**Comment by evpinheiro** [comment]
It's ready for your view :)

- A phrase was added to the objective function comment.
- Added a comment and I tiny modification in defining the vars with pulp implementation. Please, feel free to revert if you don't like that, or just say to me that I do it.
- Aggregate an image of the solution in the REDME of the doc. I know it is not the pattern, but it can be an improvement.

**Comment by astersantana** [comment]
Thanks, @evpinheiro!
It looks great. I kept everything you suggested, just changed the wording of the objective function a little bit.
Welcome to the Mip Master community!

**Pull request merged**
